// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-invoices.ts
import { createClient } from "npm:@supabase/supabase-js@^2.56.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_invoices_default = defineTool({
  name: "list_invoices",
  title: "List invoices",
  description: "List invoices for the signed-in Servio user. Supports filtering by status (paid, pending, overdue) and limiting results.",
  inputSchema: {
    status: z.enum(["paid", "pending", "overdue"]).optional().describe("Optional invoice status filter."),
    limit: z.number().int().min(1).max(100).optional().describe("Max number of rows (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = supabaseForUser(ctx).from("invoices").select("id, invoice_number, supplier, amount, vat_amount, status, invoice_date, due_date").order("invoice_date", { ascending: false }).limit(limit ?? 25);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { invoices: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-receipts.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.56.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_receipts_default = defineTool2({
  name: "list_receipts",
  title: "List receipts",
  description: "List receipts (bonnetjes) for the signed-in Servio user.",
  inputSchema: {
    category: z2.string().optional().describe("Optional category filter."),
    limit: z2.number().int().min(1).max(100).optional().describe("Max number of rows (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = supabaseForUser2(ctx).from("receipts").select("id, merchant, amount, category, date, description").order("date", { ascending: false }).limit(limit ?? 25);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { receipts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-customers.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.56.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_customers_default = defineTool3({
  name: "list_customers",
  title: "List customers",
  description: "List customers (klanten) for the signed-in Servio user. Supports free-text search on name/email.",
  inputSchema: {
    search: z3.string().optional().describe("Optional search term for name or email."),
    limit: z3.number().int().min(1).max(100).optional().describe("Max number of rows (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = supabaseForUser3(ctx).from("customers").select("id, name, email, phone, company, vat_number, created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (search) q = q.or(`name.ilike.%${search}%,email.ilike.%${search}%,company.ilike.%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { customers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/financial-summary.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.56.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var financial_summary_default = defineTool4({
  name: "financial_summary",
  title: "Financial summary",
  description: "Return a summary of income, expenses, net profit and VAT for the signed-in user over a given period (default: current month).",
  inputSchema: {
    period: z4.enum(["month", "quarter", "year"]).optional().describe("Time window (default: month).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ period }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const now = /* @__PURE__ */ new Date();
    let start;
    if (period === "year") start = new Date(now.getFullYear(), 0, 1);
    else if (period === "quarter") start = new Date(now.getFullYear(), Math.floor(now.getMonth() / 3) * 3, 1);
    else start = new Date(now.getFullYear(), now.getMonth(), 1);
    const supabase = supabaseForUser4(ctx);
    const [tx, inv] = await Promise.all([
      supabase.from("transactions").select("amount, type, date").gte("date", start.toISOString().slice(0, 10)),
      supabase.from("invoices").select("amount, vat_amount, status, invoice_date").gte("invoice_date", start.toISOString().slice(0, 10))
    ]);
    if (tx.error) return { content: [{ type: "text", text: tx.error.message }], isError: true };
    if (inv.error) return { content: [{ type: "text", text: inv.error.message }], isError: true };
    const income = (tx.data ?? []).filter((t) => t.type === "income").reduce((s, t) => s + Number(t.amount ?? 0), 0);
    const expenses = (tx.data ?? []).filter((t) => t.type === "expense").reduce((s, t) => s + Number(t.amount ?? 0), 0);
    const vat = (inv.data ?? []).reduce((s, i) => s + Number(i.vat_amount ?? 0), 0);
    const invoicesTotal = (inv.data ?? []).reduce((s, i) => s + Number(i.amount ?? 0), 0);
    const overdue = (inv.data ?? []).filter((i) => i.status === "overdue").length;
    const summary = {
      period: period ?? "month",
      since: start.toISOString().slice(0, 10),
      income: Number(income.toFixed(2)),
      expenses: Number(expenses.toFixed(2)),
      net_profit: Number((income - expenses).toFixed(2)),
      vat_reserved: Number(vat.toFixed(2)),
      invoices_total: Number(invoicesTotal.toFixed(2)),
      overdue_invoices: overdue
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "avtzjxknxnajzutcoayl";
var mcp_default = defineMcp({
  name: "servio-mcp",
  title: "Servio",
  version: "0.1.0",
  instructions: "Servio tools for the signed-in user's accounting data: list invoices, receipts and customers, and get a financial summary. All tools operate on the caller's own data (RLS).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_invoices_default, list_receipts_default, list_customers_default, financial_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
